######################## default configuration ####################
baseURL = "https://wasmcloud.com/"
title = "wasmcloud - Why stop at the edge?"
theme = "copper-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "UA-190314505-1" # example : UA-123-45
# disqus short name
disqusShortname = "wasmcloud" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

#################### default parameters ################################
[params]
logo = "images/wasmcloud-logo.png"
# Meta data
description = "wasmCloud Logo"
author = "Wasmcloud LLC"
# contact form action
contact_form_action = "https://formspree.io/f/moqpzbpd" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.png" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
name = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/wasmcloud/"

[[params.social]]
name = "twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/wasmcloud"

[[params.social]]
name = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/wasmCloud"

[[params.social]]
name = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/WasmCloud-102542298375661/"



################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
footer_content = "wasmcloud is proudly open source.  A secure, portable runtime for building microservices quickly with wasm on cloud and edge."
# copyright
copyright = "2021 Â© wasmCloud Project Authors. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page: [https://www.linuxfoundation.org/trademark-usage](https://www.linuxfoundation.org/trademark-usage)"



############### English navigation ################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Try Now"
URL = "https://labs.cosmonic.com"
weight = 2

  [[Languages.en.menu.main]]
  parent = "Try Now"
  name = "Cosmonic Labs"
  URL = "https://labs.cosmonic.com"

  [[Languages.en.menu.main]]
  parent = "Try Now"
  name = "wasmCloud Class Online"
  URL = "https://training.linuxfoundation.org/training/webassembly-actors-from-cloud-to-edge-lfd134x/"




[[Languages.en.menu.main]]
name = "Get wasmCloud"
weight = 3
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Get wasmCloud"
  name = "Install"
  URL = "https://wasmcloud.dev/overview/installation/"

  [[Languages.en.menu.main]]
  parent = "Get wasmCloud"
  name = "Github"
  URL = "https://github.com/wasmcloud/"
 
[[Languages.en.menu.main]]
name = "Community"
URL = "https://slack.wasmCloud.com"
weight = 4
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Community"
  name = "Slack"
  URL = "https://slack.wasmCloud.com"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Community"
  name = "Calendar"
  URL = "https://calendar.google.com/calendar/u/0/embed?src=c_6cm5hud8evuns4pe5ggu3h9qrs@group.calendar.google.com"
  weight = 2 
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Pricing 2"
#  URL = "pricing-2"

[[Languages.en.menu.main]]
name = "Documentation"
URL = "https://wasmcloud.dev/"
weight = 5

#  [[Languages.en.menu.main]]
#  parent = "Documentation"
#  name = "FAQ"
#  URL = "faq"

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 7

#[[Languages.en.menu.main]]
#name = "Services"
#URL = "services"
#weight = 5

#[[Languages.en.menu.main]]
#name = "Team"
#URL = "team"
#weight = 4

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 8


#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Career"
#  URL = "career"

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Pricing"
#  URL = "pricing"
  
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Pricing 2"
#  URL = "pricing-2"
  
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "How It Works"
#  URL = "how-it-works"
  
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Testimonial"
#  URL = "testimonial"
  
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Faq"
#  URL = "faq"
  
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Changelog"
#  URL = "changelog"

# Footer menu
#[[Languages.en.menu.footer]]
#name = "Faq"
#URL = "faq"
#weight = 1

[[Languages.en.menu.footer]]
subscription = true


[[Languages.en.menu.footer]]
name = "Terms & Conditions"
URL = "terms-conditions"
weight = 2

[[Languages.en.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 3

