redirects = [
  { from = "/about", to = "/", status = 301 },

  { from = "/cloud", to = "/docs/production/k8s/", status = 301 },

  { from = "/docs", to = "/docs/intro", status = 301 },

  { from = "/docs/app-dev", to = "/docs/fundamentals/interface_driven_development", status = 301 },
  { from = "/docs/app-dev/a2a", to = "/docs/fundamentals/actors/a2a", status = 301 },
  { from = "/docs/app-dev/create-actor", to = "/docs/fundamentals/actors/create-actor/", status = 301 },
  { from = "/docs/app-dev/create-actor/generate", to = "/docs/fundamentals/actors/create-actor/generate", status = 301 },
  { from = "/docs/app-dev/create-actor/run", to = "/docs/fundamentals/actors/create-actor/run", status = 301 },
  { from = "/docs/app-dev/create-actor/update", to = "/docs/fundamentals/actors/create-actor/run", status = 301 },
  { from = "/docs/app-dev/create-provider", to = "/docs/fundamentals/capabilities/create-provider/", status = 301 },
  { from = "/docs/app-dev/secure/clusterkeys", to = "/docs/production/secure/clusterkeys#zero-trust-invocations", status = 301 },
  { from = "/docs/app-dev/std-caps", to = "/docs/fundamentals/capabilities", status = 301 },

  { from = "/docs/category/actors", to = "/docs/concepts/actors", status = 301 },
  { from = "/docs/category/capabilities", to = "/docs/concepts/capabilities", status = 301 },
  { from = "/docs/category/fundamentals", to = "/docs/concepts/actors", status = 301 },
  { from = "/docs/category/getting-started", to = "/docs/tour/hello-world", status = 301 },
  { from = "/docs/category/managed-application-deployment-wadm", to = "/docs/category/declarative-application-deployment-wadm", status = 301 },
  { from = "/docs/category/reference", to = "/docs/reference/config", status = 301 },
  { from = "/docs/category/reference/host-runtime/capabilities", to = "/docs/fundamentals/capabilities", status = 301 },
  { from = "/docs/category/reference/lattice", to = "/docs/deployment/lattice", status = 301 },
  { from = "/docs/category/runtime-linking", to = "/docs/concepts/runtime-linking/link-definitions", status = 301 },
  { from = "/docs/category/securing-applications", to = "/docs/deployment/lattice/security-patterns", status = 301 },
  { from = "/docs/category/wasmcloud-in-production", to = "/docs/deployment", status = 301 },

  { from = "/docs/docs/getting-started", to = "/docs/installation", status = 301 },

  { from = "/docs/downloads", to = "/docs/installation", status = 301 },

  { from = "/docs/faq", to = "/docs/reference/faq", status = 301 },

  { from = "/docs/fundamentals/actors", to = "/docs/concepts/actors", status = 301 },
  { from = "/docs/fundamentals/actors/a2a", to = "/docs/developer/communication/actor-to-actor-calls", status = 301 },
  { from = "/docs/fundamentals/actors/create-actor", to = "/docs/developer/actors", status = 301 },
  { from = "/docs/fundamentals/actors/create-actor/generate", to = "/docs/developer/actors/generate", status = 301 },
  { from = "/docs/fundamentals/actors/create-actor/run", to = "/docs/developer/actors/run", status = 301 },
  { from = "/docs/fundamentals/actors/create-actor/update", to = "/docs/developer/actors/update", status = 301 },
  { from = "/docs/fundamentals/actors/test", to = "/docs/developer/actors/test", status = 301 },
  { from = "/docs/fundamentals/actors/update", to = "/docs/developer/actors/update", status = 301 },
  { from = "/docs/fundamentals/actors/wc_actors", to = "/docs/concepts/actors", status = 301 },
  { from = "/docs/fundamentals/capabilities", to = "/docs/concepts/capabilities", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider", to = "/docs/developer/providers", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider/consuming", to = "/docs/developer/providers/consuming", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider/create-par", to = "/docs/developer/providers/create-par", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider/new-interface", to = "/docs/developer/interfaces/creating-an-interface", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider/rust", to = "/docs/developer/providers/rust", status = 301 },
  { from = "/docs/fundamentals/capabilities/create-provider/testing", to = "/docs/developer/providers/testing", status = 301 },
  { from = "/docs/fundamentals/debugging", to = "/docs/developer/debugging", status = 301 },
  { from = "/docs/fundamentals/debugging/actors", to = "/docs/developer/debugging/actors", status = 301 },
  { from = "/docs/fundamentals/debugging/host", to = "/docs/developer/debugging/host", status = 301 },
  { from = "/docs/fundamentals/debugging/providers", to = "/docs/developer/debugging/providers", status = 301 },
  { from = "/docs/fundamentals/interface_driven_development", to = "/docs/concepts/interface-driven-development", status = 301 },
  { from = "/docs/fundamentals/runtime_linking/links", to = "/docs/concepts/runtime-linking/link-definitions", status = 301 },
  { from = "/docs/fundamentals/runtime_linking/links", to = "/docs/concepts/runtime-linking/link-definitions", status = 301 },
  { from = "/docs/fundamentals/wadm", to = "/docs/ecosystem/wadm", status = 301 },
  { from = "/docs/fundamentals/wadm/api", to = "/docs/ecosystem/wadm/api", status = 301 },
  { from = "/docs/fundamentals/wadm/deploying", to = "/docs/ecosystem/wadm/deploying", status = 301 },
  { from = "/docs/fundamentals/wadm/model", to = "/docs/ecosystem/wadm/model", status = 301 },
  { from = "/docs/fundamentals/wadm/model", to = "/docs/ecosystem/wadm/model", status = 301 },
  { from = "/docs/fundamentals/wadm/usage", to = "/docs/ecosystem/wadm/usage", status = 301 },
  { from = "/docs/fundamentals/wash", to = "/docs/ecosystem/wash", status = 301 },
  { from = "/docs/fundamentals/wash/contexts", to = "/docs/ecosystem/wash/contexts", status = 301 },
  { from = "/docs/fundamentals/workflow", to = "/docs/developer/workflow", status = 301 },
  { from = "/docs/fundamentals/workflow/config", to = "/docs/reference/config", status = 301 },

  { from = "/docs/getting-started", to = "/docs/installation", status = 301 },

  { from = "/docs/hosts/elixir/host_configure", to = "/docs/hosts/elixir/host-configure", status = 301 },

  { from = "/docs/interfaces/codegen-toml", to = "/docs/hosts/abis/wasmbus/interfaces/codegen-toml", status = 301 },
  { from = "/docs/interfaces/crates-io", to = "/docs/hosts/abis/wasmbus/interfaces/crates-io", status = 301 },

  { from = "/docs/overview/getting-started", to = "/docs/installation", status = 301 },
  { from = "/docs/overview/installation", to = "/docs/installation", status = 301 },
  { from = "/docs/overview/installation/install-with-docker", to = "/docs/installation?os=docker", status = 301 },

  { from = "/docs/platform-builder", to = "/docs/installation", status = 301 },
  { from = "/docs/platform-builder/docker", to = "/docs/installation?os=docker", status = 301 },

  { from = "/docs/production", to = "/docs/deployment", status = 301 },
  { from = "/docs/production/k8s", to = "/docs/deployment/k8s", status = 301 },
  { from = "/docs/production/lattice", to = "/docs/deployment/lattice", status = 301 },
  { from = "/docs/production/lattice/auctions", to = "/docs/deployment/lattice/auctions", status = 301 },
  { from = "/docs/production/lattice/jetstream", to = "/docs/deployment/lattice/jetstream", status = 301 },
  { from = "/docs/production/lattice/js_leaf", to = "/docs/deployment/lattice/js-leaf", status = 301 },
  { from = "/docs/production/lattice/leaf-nodes", to = "/docs/deployment/lattice/leaf-nodes", status = 301 },
  { from = "/docs/production/lattice/ngs", to = "/docs/deployment/lattice/ngs", status = 301 },
  { from = "/docs/production/lattice/provision", to = "/docs/deployment/lattice/provision", status = 301 },
  { from = "/docs/production/lattice/provision", to = "/docs/deployment/lattice/provision", status = 301 },
  { from = "/docs/production/lattice/security-patterns", to = "/docs/deployment/lattice/security-patterns", status = 301 },
  { from = "/docs/production/oci", to = "/docs/deployment/oci", status = 301 },
  { from = "/docs/production/oci/bindle", to = "/docs/deployment/oci/bindle", status = 301 },
  { from = "/docs/production/oci/bindle/actor-bindles", to = "/docs/deployment/oci/bindle/actor-bindles", status = 301 },
  { from = "/docs/production/oci/bindle/provider-bindles", to = "/docs/deployment/oci/bindle/provider-bindles", status = 301 },
  { from = "/docs/production/oci/bindle/using-bindles", to = "/docs/deployment/oci/bindle/using-bindles", status = 301 },
  { from = "/docs/production/secure", to = "/docs/deployment/security/nats", status = 301 },
  { from = "/docs/production/secure/clusterkeys", to = "/docs/deployment/security/clusterkeys", status = 301 },
  { from = "/docs/production/secure/env", to = "/docs/deployment/security/env", status = 301 },
  { from = "/docs/production/secure/nats", to = "/docs/deployment/security/nats", status = 301 },
  { from = "/docs/production/secure/policy", to = "/docs/deployment/tracing", status = 301 },

  { from = "/docs/reference/alternate-install-methods/install-with-docker", to = "/docs/installation?os=docker", status = 301 },
  { from = "/docs/reference/cloud_event_list", to = "/docs/reference/cloud-event-list", status = 301 },
  { from = "/docs/reference/custom/authorizers", to = "/docs/production/secure/clusterkeys#zero-trust-invocations", status = 301 },
  { from = "/docs/reference/host-runtime", to = "/docs/category/host-runtimes", status = 301 },
  { from = "/docs/reference/host-runtime/actors", to = "/docs/hosts/abis/components/", status = 301 },
  { from = "/docs/reference/host-runtime/security", to = "/docs/hosts/security", status = 301 },
  { from = "/docs/reference/lattice-protocols", to = "/docs/hosts/lattice-protocols/", status = 301 },
  { from = "/docs/reference/lattice-protocols/control-interface", to = "/docs/hosts/lattice-protocols/control-interface", status = 301 },
  { from = "/docs/reference/lattice/js_leaf", to = "/docs/deployment/lattice/js-leaf", status = 301 },
  { from = "/docs/reference/lattice/leaf-nodes", to = "/docs/deployment/lattice/leaf-nodes", status = 301 },
  { from = "/docs/reference/lattice/security-patterns", to = "/docs/deployment/lattice/security-patterns", status = 301 },
  { from = "/docs/reference/lattice", to = "/docs/deployment/lattice/", status = 301 },
  { from = "/docs/reference/wasmbus", to = "/hosts/abis/wasmbus/", status = 301 },

  { from = "/docs/releases", to = "/docs/reference/official-oci/", status = 301 },

  { from = "/docs/tour/adding_capabilities", to = "/docs/tour/adding-capabilities", status = 301 },
  { from = "/docs/tour/hello_world", to = "/docs/tour/hello-world", status = 301 },
  { from = "/docs/tour/why_wasmcloud", to = "/docs/tour/why-wasmcloud", status = 301 },

  { from = "/edge", to = "/docs/deployment/lattice/ngs", status = 301 },
]
