name: pa11y checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  pa11y-ci:
    name: Run pa11y-ci checks for wasmcloud.com sitemap.
    runs-on: ubuntu-latest
    steps:
      - name: Run pa11y-ci.
        run: npx pa11y-ci --sitemap https://wasmcloud.com/sitemap.xml .
