name: Sync example docs

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-docs:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./wasmcloud.com
      - name: Checkout Go repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./wasmcloud-go
          repository: wasmCloud/go
      - name: Sync docs
        id: sync-docs
        working-directory: ./wasmcloud.com
        run: ./scripts/update-go-docs.sh ../wasmcloud-go
      - name: Create Docs PR
        if: steps.sync-docs.outputs.docs_changed == 'true'
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          path: ./wasmcloud.com
          base: main
          commit-message: Updates Go example docs from wasmcloud-go
          title: 'chore: Update Go example docs'
          body: Updates Go example docs from wasmcloud-go. This is an automatic PR.
          branch: chore/update-go-example-docs
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
