name: Sync example docs (rust)

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sync-examples-rust.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-docs-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./wasmcloud.com

      - name: Checkout wasmCloud repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./wasmcloud
          repository: wasmCloud/wasmCloud

      - name: Sync docs
        id: sync-docs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { updateDocs } = await import("${{ github.workspace }}/wasmcloud.com/scripts/update-docs.mjs");
            await updateDocs({
              outputFolder: "./wasmcloud.com/docs/examples/rust",
              readmePaths: [
                "./wasmcloud/examples/rust/components/**/README.md",
                "./wasmcloud/examples/rust/providers/messaging-nats/README.md",
              ],
              skipProjects: [
                "echo-messaging-0-3-0",
              ],
            })

      - name: Create Docs PR
        id: create-pr
        if: github.event_name != 'pull_request' && steps.sync-docs.outputs.docs_changed == 'true'
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          path: ./wasmcloud.com
          base: main
          commit-message: Updates Rust example docs from wasmcloud
          title: 'chore: Update Rust example docs'
          body: |
            Updates Rust example docs from wasmcloud-go. This is an automatically generated PR.
          branch: chore/update-rust-example-docs
          delete-branch: true
          author: wasmCloud Automation Bot <151542377+wasmcloud-automation-app[bot]@users.noreply.github.com>
          committer: wasmCloud Automation Bot <151542377+wasmcloud-automation-app[bot]@users.noreply.github.com>
          signoff: true

      - name: Workflow Summary
        id: workflow-summary
        if: ${{ always() }}
        env:
          UPDATE_DOCS: ${{ steps.sync-docs.outcome }}
          PR_CREATION: ${{ steps.create-pr.outcome }}
          ANY_CHANGED: ${{ steps.sync-docs.outputs.docs_changed }}
        run: | #shell
          echo "### Docs Sync Result" >> $GITHUB_STEP_SUMMARY

          case "$UPDATE_DOCS" in
            success)   echo "- âœ… \`updateDocs()\` was called and completed successfully" >> $GITHUB_STEP_SUMMARY;;
            skipped)   echo "- â­ï¸ \`updateDocs()\` was skipped" >> $GITHUB_STEP_SUMMARY;;
            cancelled) echo "- ðŸš« \`updateDocs()\` was cancelled" >> $GITHUB_STEP_SUMMARY;;
            failure)   echo "- âŒ \`updateDocs()\` failed" >> $GITHUB_STEP_SUMMARY;;
          esac

          case "$ANY_CHANGED" in
            false) echo "- ðŸŸ° Docs were not changed (not a problem, probably just nothing new)" >> $GITHUB_STEP_SUMMARY;;
            true) echo "- âœ… Docs were changed" >> $GITHUB_STEP_SUMMARY;;
          esac

          case "$PR_CREATION" in
            success)   echo "- âœ… PR created" >> $GITHUB_STEP_SUMMARY;;
            skipped)   echo "- â­ï¸ PR creation was skipped" >> $GITHUB_STEP_SUMMARY;;
            cancelled) echo "- ðŸš« PR creation was cancelled" >> $GITHUB_STEP_SUMMARY;;
            failure)   echo "- âŒ PR creation failed" >> $GITHUB_STEP_SUMMARY;;
          esac

          echo "" >> $GITHUB_STEP_SUMMARY